### ISSUE TITLE
Using uinput instead of create_pointer/touch?

### ISSUE THREAD

**Issue by jexposit** [canonical/wlcs#336]
Hi!

In order to integrate wlcs into a compositor, it is required to implement functions to handle emulation of pointer and touch devices. I imagine keyboard, tablet and other devices will be required in the future.

Is there a reason to not use uinput instead?
https://kernel.org/doc/html/latest/input/uinput.html

uinput allows to emulate input devices from userspace. The only caveat is that root permissions are required.

Would it be possible to use uinput in wlcs to reduce integration code? Is there a technical reason (root?) I'm missing that doesn't allow to use uinput?

**Comment by RAOF** [comment]
So, one of the reasons that we use compositor hooks to handle pointer/touch emulation is that we need pixel-accurate results. For touch devices that's *maybe* possible (I think there are ways it can break, but it's at least fairly tractable). For pointer it's fundamentally the wrong layer - the evdev events get significantly processed between the kernel and the compositor via acceleration curves, and so on.

When and if we have keyboard tests, we may well use uinput (or possibly libei, or something) for that, as they don't have the same constraints.

**Comment by jexposit** [comment]
Hey @RAOF 

Thanks a lot for the explanation. 

That makes a lot of sense, I didn't think of acceleration profiles and how they'd make really difficult to position the pointer in the correct place.

Closing the issue.

**Comment by Saviq** [comment]
One other reason is running the tests in parallel, it would be much more difficult to get input into the intended compositor. And on top of that, you're testing more than the compositor itself.

You could, in theory, imagine a compositor that didn't even take kernel input events.
